clc;
clear;
close all;

load('multicentricTableAllImprovedOnlyRev04.mat');

% In this example case, the table does not include a score fields. Thus the
% table needs to be formated.
tableMulticentric = renamevars(tableMulticentric, 'efficiency', 'clinicalScore');

psmNguyenAll = PSM(tableMulticentric, ...
    'mode', 'analysis', ...
    'algorithm', 'Nguyen2019', ...
    'hemisphere', 'both', ...
    'bypassCheck', true);

psmNguyenAll.pipeline.validation = { ...
    @(method, ratio) obj.util_getValidPartition( ...
        'Out-of-sample', ...
        0.2)};

psmDembekAll = PSM(tableMulticentric, ...
    'mode', 'analysis', ...
    'algorithm', 'Dembek2019', ...
    'hemisphere', 'both', ...
    'bypassCheck', true);

psmDembekAll.pipeline.validation = { ...
    @(method, ratio) obj.util_getValidPartition( ...
        'Out-of-sample', ...
        0.2)};

psmReichAll = PSM(tableMulticentric, ...
    'mode', 'analysis', ...
    'algorithm', 'Reich2019', ...
    'hemisphere', 'both', ...
    'bypassCheck', true);

psmReichAll.pipeline.validation = { ...
    @(method, ratio) obj.util_getValidPartition( ...
        'Out-of-sample', ...
        0.2)};

% Compute the maps
psmNguyenAll.compute();
psmNguyenAll.evaluate();

psmDembekAll.compute();
psmDembekAll.evaluate();

psmReichAll.compute();
psmReichAll.evaluate();

%%

% TODO
%   - on full data set
%   - on hemispheric data set
%   - less data
