% load table

%% Image result 1

load('../../03_Data/01_Tables/multicentricTableAllImprovedOnlyRev05.mat');

psm = PSM(tableMulticentric, ...
    'algorithm', 'Nguyen2019', ...
    'hemisphere', 'Both', ...
    'bypassCheck', true, ...
    'centerID', 0, ...
    'mode', 'analysis');

psm.createPreprocessedCSV;
